# Generated by Django 6.0.1 on 2026-01-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('kind', models.CharField(choices=[('audio', 'Audio (MP3)'), ('video', 'Video (URL/MP4)')], default='audio', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='library/%Y/%m/')),
                ('video_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='library_covers/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
