# Generated by Django 6.0.1 on 2026-01-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='library_tracks/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.mediaitem')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('item', 'order'), name='uniq_media_track_order_per_item')],
            },
        ),
    ]
